# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2018-06-02 12:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20180531_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
